[package]
name = "lmc_compiler"
version = "0.1.0"
authors = ["Timothy Aleem <timothy@precess.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
lazy_static = "1.1.1"
bitvec = "0.17.4"
